name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory
      SONAR_SCANNER_PROJECT_KEY: sydneyegg_cppAndcSharp

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

      - name: SonarScanner for .NET - Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin `
            /k:"${{ env.SONAR_SCANNER_PROJECT_KEY }}" `
            /o:"sydneyegg" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore .NET dependencies
        run: dotnet restore CPlusPlusAndCSharp.sln

      - name: Build Solution with Build Wrapper
        run: |
          build-wrapper-win-x86-64 --out-dir $env:BUILD_WRAPPER_OUT_DIR msbuild CPlusPlusAndCSharp.sln /p:Configuration=Release
        shell: pwsh

      - name: SonarScanner for .NET - End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
